name: Deploy Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Select Envirionment to deploy '
        required: true
      choice:
        type: choice
        options:
        - e1
        - e2
        - e3


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: greet
      - run: |
          echo " environment is ${{ github.event.environment }}"
