name: Dispatch Workflow

on: 
  workflow_dispatch:
    inputs:
      Project:
        type: project
        description: Select the project
      choice:
        options:
        - one-data
        - one-data-staging  
      environment:
        type: choice
        description: select the environment
        options:
        - E1
        - E2
        - E3


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: greet
        run: |
          echo " environment is ${{ github.event.environment }}"
