name: Java Maven Build & Publish Artifact
run-name: ${{ github.actor }} is building out github repository
on: 
  push:
    branches: ["main"]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - run: echo "The job was automatically triggered by a ${{github.event_name }} event."
    - run: echo " This job is now running on a ${{ runner.os }} server hosted on Github"
    - run: echo " The name of your branch is ${{ github.ref }} and repository is ${{ github.repository }}."
    - name: Check out repostiory code
      uses: actions/checkout@v4
    - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo " The workflow is now ready to test code in runner. "
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
